version: '3'

volumes:
  taski_pg_data:
  taski_static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - taski_pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - taski_static:/backend_static
  frontend:
    build: ./frontend/
    env_file: .env
    volumes:
      - taski_static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    build: ./gateway/
    volumes:
      - taski_static:/staticfiles/
    ports:
      - 8000:80 
